export const COUNT_YEAR= 'COUNT_YEAR'
export const SET_INTEREST_ACCRUALS= 'SET_INTEREST_ACCRUALS'
export const SET_PERIODICITY= 'SET_PERIODICITY'
export const SET_REPLENISHMENT= 'SET_REPLENISHMENT'
export const SET_INITIAL_AMOUNT= 'SET_INITIAL_AMOUNT'


